version: '3'

services:
  server:
    container_name: server_apex
    build: ./services/server
    environment:
      BASE_URL: /api
    ports:
      - 5000:5000
    command: uvicorn src.main:app --host 0.0.0.0 --port 5000

  client:
    container_name: client_apex
    build:
      context: ./services/client
      dockerfile: Dockerfile.Prod
    ports:
      - 8080:8080
        #environment:
        #  BASE_URL: /api
    command: npm run build
