version: '3'

services:
  server:
    container_name: server_apex
    build: ./services/server
    environment:
      DATABASE_URL: postgres://apex_fastapi:LGIKLKks87hk65T@db:5432/apex_fastapi
      BASE_URL: /api
    ports:
      - 5000:5000
    command: uvicorn src.main:app --host 0.0.0.0 --port 5000
    depends_on:
      - db

  client:
    container_name: client_apex
    build:
      context: ./services/client
      dockerfile: Dockerfile.Prod
    ports:
      - 8080:8080
        #environment:
        #  BASE_URL: /api
    command: npm run build
    depends_on:
      - backend

  db:
    container_name: apex_database_pg
    image: postgres:14-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: apex_fastapi
      POSTGRES_PASSWORD: LGIKLKks87hk65T
      POSTGRES_DB: apex_fastapi
    volumes:
      - postgres_apex:/var/lib/postgresql/data/

volumes:
  postgres_apex:
