version: '3'

services:
  server:
    container_name: server_apex
    build:
      context: ./services/server
      dockerfile: Dockerfile.Prod
    environment:
      DATABASE_URL: postgres://apex_fastapi:LGIKLKks87hk65T@db:5432/apex_fastapi
      ROOT_PATH: /api
      BASE_URL: http://localhost:8090
    expose:
      - 5001
    command: uvicorn src.main:app --host 0.0.0.0 --port 5001
    depends_on:
      - db

  client:
    container_name: client_apex
    build:
      context: ./services/client
      dockerfile: Dockerfile.Prod
    ports:
      - 8090:8090
    command: nginx
    environment:
      BASE_URL: /api
    depends_on:
      - server

  db:
    container_name: apex_database_pg
    image: postgres:14-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: apex_fastapi
      POSTGRES_PASSWORD: LGIKLKks87hk65T
      POSTGRES_DB: apex_fastapi
    volumes:
      - postgres_apex:/var/lib/postgresql/data/

volumes:
  postgres_apex:
