version: '3'

services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile.Dev
    volumes:
      - ./services/server:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5001
    ports:
      - 5001:5001
    environment:
      BASE_URL: http://localhost:8090
      ROOT_PATH: /
        #DEBUG: False
      DB_NAME: apex_fastapi_dev

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile.Dev
    stdin_open: true
    tty: true
    volumes:
      - './services/client:/app'
      - '/usr/src/app/services/client/node_modules'
    environment:
      BASE_URL: localhost:5001
    command: npm run dev

  db:
    environment:
      POSTGRES_USER: apex_fastapi
      POSTGRES_PASSWORD: LGIKLKks87hk65T
      POSTGRES_DB: apex_fastapi_dev
    volumes:
      #- postgres_apex_dev:/var/lib/postgresql/data/
      - postgres_apex_dev2:/var/lib/postgresql/data/

volumes:
  #postgres_apex_dev:
  postgres_apex_dev2:
