-- upgrade --
CREATE TABLE IF NOT EXISTS "records" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "blocked_acess" SMALLINT NOT NULL  DEFAULT 0,
    "age_limit" SMALLINT NOT NULL  DEFAULT 0,
    "theam_restriction" SMALLINT NOT NULL  DEFAULT 21
);
COMMENT ON COLUMN "records"."blocked_acess" IS 'ALLOW: 0\nDENY: 1';
COMMENT ON COLUMN "records"."age_limit" IS 'NULL: 0\nSIX: 1\nTWELVE: 2\nSIXTEEN: 3\nXXX: 4';
COMMENT ON COLUMN "records"."theam_restriction" IS 'BUSINESS: 0\nMALICIOUS_SITE: 1\nFOR_CHILD: 2\nFILE_DOWNLOAD: 3\nHEALTH: 4\nGAME_ENTERTAINMENT: 5\nCULTURE: 6\nMULTIMEDIA: 7\nSCIENCE_AND_TECHNOLOGY: 8\nPROFANITY: 9\nNEWS_AND_MEDIA: 10\nEDUCATION: 11\nSOCIETY_AND_POLITICS: 12\nSEARCH_ENGINES: 13\nUSER_CONTENT: 14\nPROXIES_AND_ANONYMIZERS: 15\nILLEGAL_WEBSITES: 16\nADVERTISING_AND_MARKETING: 17\nSOCIAL_NETWORKS: 18\nSPORTS_AND_HOBBIES: 19\nBACKGROUND_INFORMATION: 20\nNON_THEAM: 21';
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSONB NOT NULL
);
