kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: local
    app.kubernetes.io/name: backup-pv
  name: backup-pv
  namespace: apexfastapi
spec:
  capacity:
   storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-backup-storage
  local:
    path: /mnt/postgres_backup
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-node1
