apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo-ha
  namespace: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.6-2
  postgresVersion: 14
  instances:
    - name: pgha1
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: local-postgres-ha-storage
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
              #affinity:
              #  podAntiAffinity:
              #    preferredDuringSchedulingIgnoredDuringExecution:
              #    - weight: 1
              #      podAffinityTerm:
              #        topologyKey: kubernetes.io/hostname
              #        labelSelector:
              #          matchLabels:
              #            postgres-operator.crunchydata.com/cluster: hippo-ha
              #            postgres-operator.crunchydata.com/instance-set: pgha1
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: local-backup-storage-ha
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.17-5
      replicas: 1

  service:
    type: ClusterIP
      #  ports:
      #    - name: patroni
      #      port: 8008
      #      targetPort: 8008

          #affinity:
          #  podAntiAffinity:
          #    preferredDuringSchedulingIgnoredDuringExecution:
          #    - weight: 1
          #      podAffinityTerm:
          #        topologyKey: kubernetes.io/hostname
          #        labelSelector:
          #          matchLabels:
          #            postgres-operator.crunchydata.com/cluster: hippo-ha
          #            postgres-operator.crunchydata.com/role: pgbouncer
