apiVersion: batch/v1
kind: Job
metadata:
  name: "migration-job"
  namespace: apexfastapi
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "migration-job-pod"
    spec:
      restartPolicy: Never
      containers:
      - name: db-migrations
        image: lenow/kuber_apex_vite_server:v1.1
        env:
          - name: DB_HOST
            valueFrom: {secretKeyRef: {name: postgres-cluster-pguser-apexfastapi, key: host}}
          - name: DB_PORT
            valueFrom: {secretKeyRef: {name: postgres-cluster-pguser-apexfastapi, key: port}}
          - name: DB_USER
            valueFrom: {secretKeyRef: {name: postgres-cluster-pguser-apexfastapi, key: user}}
          - name: DB_PASSWORD
            valueFrom: {secretKeyRef: {name: postgres-cluster-pguser-apexfastapi, key: password}}
          - name: DB_NAME
            valueFrom: {secretKeyRef: {name: postgres-cluster-pguser-apexfastapi, key: dbname}}
        command: ["/bin/sh", "-c"]
        args:
          - aerich init -t src.database.config.TORTOISE_ORM && aerich init-db
        volumeMounts:
         - name: migrations
           mountPath: "/migrations/"
      volumes:
        - name: migrations
