apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: apexfastapi
data:
  POSTGRES_USER: YXBleF9mYXN0YXBp      # apex_fastapi
  POSTGRES_PASSWORD: TEdJS0xLa3M4N2hrNjVU   # LGIKLKks87hk65T
  POSTGRES_DB: YXBleF9kYg==                   # apex_db

