apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: hippo-ha
    postgres-operator.crunchydata.com/role: pgbouncer
  name: hippo-ha-pgbouncer
  namespace: hippo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/cluster: hippo-ha
      postgres-operator.crunchydata.com/role: pgbouncer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        postgres-operator.crunchydata.com/cluster: hippo-ha
        postgres-operator.crunchydata.com/role: pgbouncer
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - pgbouncer
        - /etc/pgbouncer/~postgres-operator.ini
        image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.17-5
        imagePullPolicy: IfNotPresent
        name: pgbouncer
        ports:
        - containerPort: 5432
          name: pgbouncer
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pgbouncer
          name: pgbouncer-config
          readOnly: true
      - command:
        - bash
        - -ceu
        - --
        - |-
          monitor() {
          exec {fd}<> <(:)
          while read -r -t 5 -u "${fd}" || true; do
            if [ "${directory}" -nt "/proc/self/fd/${fd}" ] && pkill -HUP --exact pgbouncer
            then
              exec {fd}>&- && exec {fd}<> <(:)
              stat --format='Loaded configuration dated %y' "${directory}"
            fi
          done
          }; export directory="$1"; export -f monitor; exec -a "$0" bash -ceu monitor
        - pgbouncer-config
        - /etc/pgbouncer
        image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.17-5
        imagePullPolicy: IfNotPresent
        name: pgbouncer-config
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pgbouncer
          name: pgbouncer-config
          readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            postgres-operator.crunchydata.com/cluster: hippo-ha
            postgres-operator.crunchydata.com/role: pgbouncer
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      - labelSelector:
          matchLabels:
            postgres-operator.crunchydata.com/cluster: hippo-ha
            postgres-operator.crunchydata.com/role: pgbouncer
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - name: pgbouncer-config
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: pgbouncer-empty
                path: pgbouncer.ini
              name: hippo-ha-pgbouncer
          - configMap:
              items:
              - key: pgbouncer.ini
                path: ~postgres-operator.ini
              name: hippo-ha-pgbouncer
          - secret:
              items:
              - key: pgbouncer-users.txt
                path: ~postgres-operator/users.txt
              name: hippo-ha-pgbouncer
          - secret:
              items:
              - key: pgbouncer-frontend.ca-roots
                path: ~postgres-operator/frontend-ca.crt
              - key: pgbouncer-frontend.key
                path: ~postgres-operator/frontend-tls.key
              - key: pgbouncer-frontend.crt
                path: ~postgres-operator/frontend-tls.crt
              name: hippo-ha-pgbouncer
          - secret:
              items:
              - key: ca.crt
                path: ~postgres-operator/backend-ca.crt
              name: hippo-ha-cluster-cert
