apiVersion: v1
kind: Service
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: hippo-ha
    postgres-operator.crunchydata.com/role: primary
  name: hippo-ha-primary
  namespace: hippo
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: postgres
  - name: patroni
    port: 8008
    protocol: TCP
    targetPort: 8008
  sessionAffinity: None
  type: ClusterIP
