apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: hippo-ha
    postgres-operator.crunchydata.com/instance: hippo-ha-pgha5-bqqk
    postgres-operator.crunchydata.com/instance-set: pgha5
  name: hippo-ha-pgha5-bqqk
  namespace: hippo
spec:
  replicas: 1
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/cluster: hippo-ha
      postgres-operator.crunchydata.com/instance: hippo-ha-pgha5-bqqk
      postgres-operator.crunchydata.com/instance-set: pgha5
  template:
    metadata:
      labels:
        postgres-operator.crunchydata.com/cluster: hippo-ha
        postgres-operator.crunchydata.com/instance: hippo-ha-pgha5-bqqk
        postgres-operator.crunchydata.com/instance-set: pgha5
    spec:
      containers:
      - name: test-container
        image: progrium/busybox
        command:
        - "/bin/sh"
        args:
        - "-c"
        - "sleep 100000"
      serviceAccount: hippo-ha-instance
      serviceAccountName: hippo-ha-instance
