FROM node:lts-alpine as vue-builder

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json .
COPY package-lock.json .
COPY src/ ./src
COPY public/ ./public
COPY env.d.ts .
COPY .env.production .
COPY index.html .
COPY tsconfig* ./
COPY vite.config.ts .
RUN npm install


RUN npm run build-only

FROM nginx
COPY nginx.conf /etc/nginx/
RUN mkdir /var/www
RUN mkdir /var/www/logs
COPY  --from=vue-builder /app/dist /usr/share/nginx/html
