FROM node:lts-alpine as vue-builder

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .

RUN npm run build-only

FROM nginx
COPY nginx.conf /etc/nginx/
COPY  --from=vue-builder /app/dist /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
